"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Luta_1 = require("./Relacionamento Entre Classes/Luta/Luta");
var Lutador_1 = require("./Relacionamento Entre Classes/Lutador/Lutador");
var lutadores = [];
lutadores[0] = new Lutador_1.default("Marcos Rogério", "França", 1.75, 68.9, 11, 3, 1);
lutadores[1] = new Lutador_1.default("Paulo Sérgio", "Brasil", 1.68, 57.8, 14, 2, 3);
lutadores[2] = new Lutador_1.default("Francisco Pereira", "EUA", 1.65, 80.9, 12, 2, 1);
lutadores[3] = new Lutador_1.default("João Paulo", "Austrália", 1.93, 81.6, 13, 0, 2);
lutadores[4] = new Lutador_1.default("Zé Mineiro", "Brasil", 1.70, 119.3, 5, 4, 3);
lutadores[5] = new Lutador_1.default("Glauber Silva", "EUA", 1.81, 105.7, 12, 2, 4);
var UEC01 = new Luta_1.Luta();
UEC01.marcarLuta(lutadores[4], lutadores[5]);
UEC01.lutar();
