"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Livro_1 = require("./Exerc\u00EDcio - 9b/Livro/Livro");
var Pessoa_1 = require("./Exerc\u00EDcio - 9b/Pessoa/Pessoa");
// let lutadores: Lutador[] = [];
// lutadores[0] = new Lutador("Marcos Rogério", "França", 1.75, 68.9, 11, 3, 1);
// lutadores[1] = new Lutador("Paulo Sérgio", "Brasil", 1.68, 57.8, 14, 2, 3);
// lutadores[2] = new Lutador("Francisco Pereira", "EUA", 1.65, 80.9, 12, 2, 1);
// lutadores[3] = new Lutador("João Paulo", "Austrália", 1.93, 81.6, 13, 0, 2);
// lutadores[4] = new Lutador("Zé Mineiro", "Brasil", 1.70, 119.3, 5, 4, 3);
// lutadores[5] = new Lutador("Glauber Silva", "EUA", 1.81, 105.7, 12, 2, 4);
// let UEC01 = new Luta();
// UEC01.marcarLuta(lutadores[4], lutadores[5]);
// UEC01.lutar();
var leitor = new Pessoa_1.default('João Paulo', 33, 'Masculino');
var livro = new Livro_1.default('A Bíblia Sagrada', 'Deus', 1000, leitor);
livro.detalhes();
livro.folhear(100);
livro.avancarPag();
livro.detalhes();
