"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// let bic = new Caneta();
// bic.modelo = 'Bic Crystal';
// bic.cor = 'Azul';
// // bic.ponta = 0.5;
// // bic.carga = 100;
// // bic.tampada = true;
// console.log(bic.escrever());
// bic.destampar();
// bic.status();
// let funcionario = new Funcionario('João Paulo', 33, false);
// funcionario.getStatus();
